"""added role column on User

Revision ID: 1c0d3f7e251b
Revises: 3ef9e0462647
Create Date: 2024-08-09 15:27:45.460334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0d3f7e251b'
down_revision = '3ef9e0462647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
