"""first migration speaker model added

Revision ID: 343fee61ae11
Revises: 
Create Date: 2024-08-09 14:11:36.788061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343fee61ae11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('contact_info', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker')
    # ### end Alembic commands ###
