"""removed role column on User

Revision ID: 3ef9e0462647
Revises: 343fee61ae11
Create Date: 2024-08-09 15:21:10.996137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef9e0462647'
down_revision = '343fee61ae11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
